# Generated by Django 6.0.1 on 2026-05-05 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимум 200 символов', max_length=200, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='URL-friendly название (латинские буквы, цифры, дефисы)', max_length=200, unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(blank=True, help_text='Необязательное описание категории', null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Отображается ли категория на сайте', verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя компонента')),
            ],
            options={
                'verbose_name': 'компонент',
                'verbose_name_plural': 'компоненты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'тип лекарства',
                'verbose_name_plural': 'типы лекарств',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Адрес доставки')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('confirmed', 'Подтвержден'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен'), ('returned', 'Возвращен')], default='pending', max_length=20, verbose_name='Статус заказа')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Дата заказа')),
                ('total_price', models.IntegerField(help_text='Итоговая стоимость всех товаров в заказе', verbose_name='Общая цена')),
                ('payment_type', models.CharField(choices=[('cash', 'Наличные при получении'), ('card', 'Банковская карта онлайн')], default='card', help_text='Способ оплаты', max_length=20, verbose_name='Тип платежа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название лекарства')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание лекарства')),
                ('price', models.IntegerField(verbose_name='Цена лекарства')),
                ('quantity', models.IntegerField(verbose_name='Количество лекарства')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Категория')),
                ('medicine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.medicinetype', verbose_name='Тип лекарства')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_medicines', to='catalog.orders', verbose_name='Заказ')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_medicines', to='catalog.product', verbose_name='Лекарство')),
            ],
            options={
                'verbose_name': 'лекарство в заказе',
                'verbose_name_plural': 'лекарства в заказах',
            },
        ),
        migrations.CreateModel(
            name='MedicineComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_components', to='catalog.component', verbose_name='Компонент')),
                ('medicine', models.ForeignKey(help_text='Ссылка на лекарство', on_delete=django.db.models.deletion.CASCADE, related_name='medicine_components', to='catalog.product', verbose_name='Лекарство')),
            ],
            options={
                'verbose_name': 'компонент лекарства',
                'verbose_name_plural': 'компоненты лекарств',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'medicine_type'], name='catalog_pro_categor_1b14bb_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='catalog_pro_price_2d2a4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ordermedicine',
            unique_together={('order', 'medicine')},
        ),
        migrations.AddIndex(
            model_name='medicinecomponent',
            index=models.Index(fields=['component', 'medicine'], name='catalog_med_compone_a2e2c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='medicinecomponent',
            unique_together={('component', 'medicine')},
        ),
    ]
