# Generated by Django 6.0.1 on 2026-05-05 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия пользователя')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Отчество пользователя')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Электронная почта')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес пользователя')),
                ('date_dirth', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=40, verbose_name='Номер телефона')),
                ('password', models.IntegerField(blank=True, null=True, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ['surname', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, help_text='Оценка от 1 до 5', null=True, verbose_name='Рейтинг')),
                ('comment', models.TextField(help_text='Текст отзыва', verbose_name='Комментарий')),
                ('reviews_date', models.DateField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product', verbose_name='Лекарство')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
                'ordering': ['-reviews_date'],
                'indexes': [models.Index(fields=['user', 'medicine'], name='catalog_use_user_id_839e3c_idx'), models.Index(fields=['reviews_date'], name='catalog_use_reviews_868a6f_idx'), models.Index(fields=['rating'], name='catalog_use_rating_793a47_idx')],
                'unique_together': {('user', 'medicine')},
            },
        ),
    ]
