# Generated by Django 6.0.1 on 2026-05-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_user_userreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL'),
        ),
    ]
