# Generated by Django 6.0.1 on 2026-05-12 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userreviews',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='userreviews',
            name='catalog_use_user_id_839e3c_idx',
        ),
        migrations.RemoveIndex(
            model_name='userreviews',
            name='catalog_use_reviews_868a6f_idx',
        ),
        migrations.RemoveIndex(
            model_name='userreviews',
            name='catalog_use_rating_793a47_idx',
        ),
        migrations.RemoveField(
            model_name='userreviews',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='userreviews',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserReviews',
        ),
    ]
