# Generated by Django 6.0.1 on 2026-05-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_userreviews_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Загрузите свою иконку (рекомендуемый размер: 64x64 пикселей)', null=True, upload_to='category_icons/', verbose_name='Иконка (изображение)'),
        ),
    ]
