# Generated by Django 6.0.1 on 2026-05-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_category_icon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите фото товара (рекомендуемый размер: 300x300 пикселей)', null=True, upload_to='product_images/', verbose_name='Изображение товара'),
        ),
    ]
